//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WF_StokPresentation.Stok_DAL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class KasaHareketler
    {
        public int HareketID { get; set; }
        public string KasaTuru { get; set; }
        public System.DateTime Tarih { get; set; }
        public string IslemTuru { get; set; }
        public int CariID { get; set; }
        public string Belge { get; set; }
        public decimal Giren { get; set; }
        public decimal Cikan { get; set; }
        public string ParaBirimi { get; set; }
        public bool Silindi { get; set; }
    
        public virtual Cariler Cariler { get; set; }
    }
}
