//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WF_StokPresentation.Stok_DAL.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StokDataEntities : DbContext
    {
        public StokDataEntities()
            : base("name=StokDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CariHareketler> CariHareketler { get; set; }
        public virtual DbSet<Cariler> Cariler { get; set; }
        public virtual DbSet<KasaHareketler> KasaHareketler { get; set; }
        public virtual DbSet<Kategoriler> Kategoriler { get; set; }
        public virtual DbSet<UrunHareketler> UrunHareketler { get; set; }
        public virtual DbSet<Urunler> Urunler { get; set; }
    }
}
