//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WF_StokPresentation.Stok_DAL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urunler()
        {
            this.UrunHareketler = new HashSet<UrunHareketler>();
        }
    
        public int UrunID { get; set; }
        public string UrunKodu { get; set; }
        public string UrunAd { get; set; }
        public int KategoriID { get; set; }
        public int Miktar { get; set; }
        public int KritikSeviye { get; set; }
        public decimal BirimFiyat { get; set; }
        public bool Silindi { get; set; }
    
        public virtual Kategoriler Kategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UrunHareketler> UrunHareketler { get; set; }
    }
}
